#### 3/4. Fill the empty cells

In [15]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

# Creating a sample dataset with 4 clusters
X, y = make_blobs(n_samples=100, n_features=3, centers=4)

# Initializing KMeans with 4 clusters
kmeans = KMeans(n_clusters=4, algorithm = 'auto')

# Fitting with inputs
kmeans = kmeans.fit(X)

# Labelling the clusters
labels = kmeans.fit_predict(X)
print(labels)

# Getting the cluster centers
C = kmeans.fit_predict(X)
print(C)

[0 2 2 1 0 3 0 0 0 2 3 3 1 2 0 3 2 1 2 2 1 1 2 3 3 1 1 3 2 2 0 0 0 1 1 1 3
 3 1 0 3 1 3 2 0 1 0 0 0 2 3 3 1 1 3 0 1 1 3 3 3 2 0 1 1 2 3 3 2 0 2 0 3 0
 3 1 2 0 1 0 2 3 3 0 2 2 2 0 2 1 1 1 1 2 0 2 2 0 0 3]
[1 2 2 0 1 3 1 1 1 2 3 3 0 2 1 3 2 0 2 2 0 0 2 3 3 0 0 3 2 2 1 1 1 0 0 0 3
 3 0 1 3 0 3 2 1 0 1 1 1 2 3 3 0 0 3 1 0 0 3 3 3 2 1 0 0 2 3 3 2 1 2 1 3 1
 3 0 2 1 0 1 2 3 3 1 2 2 2 1 2 0 0 0 0 2 1 2 2 1 1 3]


#### 5. n_jobs? 
int. 


The number of jobs to use for the computation. This works by computing each of the n_init runs in parallel.
If -1 all CPUs are used. If 1 is given, no parallel computing code is used at all, which is useful for debugging. For n_jobs below -1, (n_cpus + 1 + n_jobs) are used. Thus for n_jobs = -2, all CPUs but one are used.

#### Lab2given.py   xclara.csv

In [20]:
from copy import deepcopy
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from joblib import Parallel, delayed

# Importing the dataset
data = pd.read_csv('/home/danni/Dropbox/Year3SemA/CS4480 Data-Intensive/Lab/lab2/xclara.csv')
print("Input Data and Shape")
print(data.shape)
data.head()

Input Data and Shape
(3000, 2)


V1         V2
0   2.072345  -3.241693
1  17.936710  15.784810
2   1.083576   7.319176
3  11.120670  14.406780
4  23.711550   2.557729

In [18]:
# Getting the values and plotting it
f1 = data['V1'].values
f2 = data['V2'].values
X = np.array(list(zip(f1, f2)))

print(X)

# Euclidean Distance Caculator
def dist(a, b, ax=1):
    return np.linalg.norm(a - b, axis=ax)

# Number of clusters
k = 3
# X coordinates of random centroids
C_x = np.random.randint(0, np.max(X)-20, size=k)
# Y coordinates of random centroids
C_y = np.random.randint(0, np.max(X)-20, size=k)
C = np.array(list(zip(C_x, C_y)), dtype=np.float32)
print("Initial Centroids")
print(C)

[[  2.072345  -3.241693]
 [ 17.93671   15.78481 ]
 [  1.083576   7.319176]
 ...
 [ 64.46532  -10.50136 ]
 [ 90.72282  -12.25584 ]
 [ 64.87976  -24.87731 ]]
Initial Centroids
[[64. 15.]
 [ 7. 35.]
 [71. 62.]]


In [12]:
# To store the value of centroids when it updates
C_old = np.zeros(C.shape)
print(C_old)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
# Cluster Lables(0, 1, 2)
clusters = np.zeros(len(X))
print(clusters)

[0. 0. 0. ... 0. 0. 0.]


In [14]:
# Error func. - Distance between new centroids and old centroids
error = dist(C, C_old, None)
print(error)

124.11285187280163


In [26]:
# define 2 parallel functions
# Assigning each value to its closest cluster
def assignment(clusters,X):
    distances = dist(clusters, X)
    cluster = np.argmin(distances)
    ci = cluster
    return ci


# Finding the new centroids by taking the average value
def centroidcompute(X,ci):
    points = [X[j] for j in range(len(X)) if clusters[j] == i]
    return np.mean(points, axis=0)

# Loop will run till the error becomes zero
while error != 0:
    # 1.Assigning each value to its closest cluster
    C = assignment(C, C_old)
    # Storing the old centroid values
    C_old = deepcopy(C)
    # 2.Finding the new centroids by taking the average value
    C = Parrallel(centroidcompute(C,C_old))

TypeError: object of type 'numpy.int64' has no len()

In [6]:

    ##Assigning each value to its closest cluster
    #for i in range(len(X)):
    #    distances = dist(X[i], C)
    #    cluster = np.argmin(distances)
    #    clusters[i] = cluster
    #
    # Storing the old centroid values
    #C_old = deepcopy(C)
    #
    #
    # Finding the new centroids by taking the average value
    #for i in range(k):
    #    points = [X[j] for j in range(len(X)) if clusters[j] == i]
    #    C[i] = np.mean(points, axis=0)
    #error = dist(C, C_old, None) 
    
'''
==========================================================
scikit-learn
==========================================================
'''

from sklearn.cluster import KMeans

# Number of clusters
kmeans = KMeans(n_clusters=3)
# Fitting the input data
kmeans = kmeans.fit(X)
# Getting the cluster labels
labels = kmeans.predict(X)
# Centroid values
centroids = kmeans.cluster_centers_

# Comparing with scikit-learn centroids
print("Final Centroid Values")
print("From scratch done by us:")
print(C) # From Scratch
print("From scikit-learn package:")
print(centroids) # From sci-kit learn

Final Centroid Values
From scratch done by us:
[[73.  2.]
 [71. 16.]
 [49. 42.]]
From scikit-learn package:
[[ 69.92418447 -10.11964119]
 [ 40.68362784  59.71589274]
 [  9.4780459   10.686052  ]]
